"use client";

import { useMemo } from "react";

import { useWeeklyRecap, useRefreshRecap, type RefreshPhase } from "@/lib/queries/use-recap";
import { useMeals } from "@/lib/queries/use-meals";
import { useExercises } from "@/lib/queries/use-exercises";
import { useNotes } from "@/lib/queries/use-notes";
import { parseISODate, todayISO } from "@/components/calendar/_lib";
import { lastNDays } from "@/components/goal/_lib";
import { AccentText } from "@/components/ui/atoms/accent-text";
import { Button } from "@/components/ui/atoms/button";
import { Card } from "@/components/ui/atoms/card";
import { Chip } from "@/components/ui/atoms/chip";

const PHASE_LABEL: Record<RefreshPhase, string> = {
  idle: "",
  queued: "queued…",
  running: "running…",
  done: "updated ✓",
  error: "couldn't refresh",
};

type DayActivity = {
  iso: string;
  meals: number;
  workouts: number;
  journal: number;
  total: number;
};

const narrowDow = (iso: string) =>
  parseISODate(iso).toLocaleDateString(undefined, { weekday: "narrow" });
const dayNum = (iso: string) => parseISODate(iso).getDate();

/** A tiny labelled metric with the recap's headline numbers. */
function Stat({ label, value }: { label: string; value: number | string }) {
  return (
    <div className="min-w-0">
      <p className="truncate text-2xl font-bold capitalize leading-none text-foreground">{value}</p>
      <p className="mt-1 text-[11px] font-medium uppercase tracking-wide text-muted">{label}</p>
    </div>
  );
}

/**
 * The home hero: "Your week in review". A per-day activity bar chart (computed
 * live from the last 7 days of logs, in the Goal page's bar language) sits
 * alongside the recap's headline stats — which are precomputed by the background
 * job runner and re-generated by the Refresh button (the live queued → running
 * → done flow). No AI, no credits: pure aggregation.
 */
export function WeekReviewHero() {
  const today = todayISO();
  const days = useMemo(() => lastNDays(7, today), [today]);

  const { data: meals = [] } = useMeals(days[0], today);
  const { data: exercises = [] } = useExercises(days[0], today);
  const { data: notes = [] } = useNotes();
  const { data: recap } = useWeeklyRecap();
  const { refresh, phase } = useRefreshRecap();
  const busy = phase === "queued" || phase === "running";

  // Per-day activity over the recap's 7-day window, so the bars and the recap
  // headline numbers describe the same span.
  const activity = useMemo<DayActivity[]>(() => {
    const window = new Set(days);
    const journalByDay = new Map<string, number>();
    for (const n of notes) {
      if (n.kind !== "journal") continue;
      const day = n.entry_date ?? n.created_at.slice(0, 10);
      if (window.has(day)) journalByDay.set(day, (journalByDay.get(day) ?? 0) + 1);
    }
    return days.map((iso) => {
      const m = meals.filter((x) => x.log_date === iso).length;
      const w = exercises.filter((x) => x.log_date === iso).length;
      const j = journalByDay.get(iso) ?? 0;
      return { iso, meals: m, workouts: w, journal: j, total: m + w + j };
    });
  }, [days, meals, exercises, notes]);

  const maxTotal = Math.max(1, ...activity.map((d) => d.total));

  return (
    <Card tone="soft" padding="md" className="flex-1">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="text-[10px] font-bold uppercase tracking-[0.12em] text-grape">
            ✨ Your week <AccentText>in review</AccentText>
          </p>
          <p className="mt-1 text-xs text-muted">
            Precomputed for you — auto-refreshed every Monday.
          </p>
        </div>
        <div className="flex items-center gap-2">
          {recap && (
            <Chip tone="soft" size="sm">
              🔥 {recap.data.streak_days}-day streak
            </Chip>
          )}
          {phase !== "idle" && (
            <span className="text-xs text-muted" aria-live="polite">
              {PHASE_LABEL[phase]}
            </span>
          )}
          <Button type="button" variant="secondary" size="sm" onClick={refresh} disabled={busy}>
            {busy ? "Refreshing…" : "↻ Refresh"}
          </Button>
        </div>
      </div>

      {/* Activity bar chart — magnitude (logs/day), grape when active, faint when empty. */}
      <div className="mt-6 flex h-[104px] items-end gap-2">
        {activity.map((d) => {
          const isToday = d.iso === today;
          const heightPct = d.total === 0 ? 6 : Math.max(14, (d.total / maxTotal) * 100);
          return (
            <div key={d.iso} className="flex flex-1 flex-col items-center gap-2">
              <div className="flex h-[76px] w-full items-end">
                <div
                  className={`w-full rounded-md transition-all ${
                    d.total === 0
                      ? "bg-grape/15"
                      : isToday
                        ? "bg-grape ring-2 ring-grape/30"
                        : "bg-grape/70"
                  }`}
                  style={{ height: `${heightPct}%` }}
                  title={`${d.meals} meal${d.meals === 1 ? "" : "s"}, ${d.workouts} workout${
                    d.workouts === 1 ? "" : "s"
                  }, ${d.journal} journal`}
                />
              </div>
              <span
                className={`text-[11px] font-bold ${isToday ? "text-grape" : "text-muted"}`}
              >
                {narrowDow(d.iso)}
                <span className="ml-0.5 font-medium text-muted/70">{dayNum(d.iso)}</span>
              </span>
            </div>
          );
        })}
      </div>

      {/* Headline stats — from the recap (the job's output). */}
      {recap ? (
        <div className="mt-6 grid grid-cols-3 gap-4 border-t border-border/40 pt-5 tablet:grid-cols-5">
          <Stat label="Active days" value={`${recap.data.active_days}/7`} />
          <Stat label="Meals" value={recap.data.meals_logged} />
          <Stat label="Workouts" value={recap.data.workouts_logged} />
          <Stat label="Journal" value={recap.data.journal_entries} />
          {recap.data.top_mood && <Stat label="Top mood" value={recap.data.top_mood} />}
        </div>
      ) : (
        <p className="mt-6 border-t border-border/40 pt-5 text-sm text-muted">
          No recap yet — hit <span className="font-semibold text-foreground">Refresh</span> to
          generate your first week in review.
        </p>
      )}
    </Card>
  );
}
