"""create daily_summaries table

Revision ID: 3ecbe3e132a5
Revises: 3465d152b111
Create Date: 2026-07-28 12:16:25.362102

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3ecbe3e132a5'
down_revision: str | Sequence[str] | None = '3465d152b111'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('calories_in', sa.Integer(), nullable=False),
    sa.Column('calories_out', sa.Integer(), nullable=False),
    sa.Column('target_calories', sa.Integer(), nullable=True),
    sa.Column('assessment', sa.String(length=16), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=False),
    sa.Column('tip', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'summary_date', name='uq_daily_summary_user_date')
    )
    op.create_index(op.f('ix_daily_summaries_summary_date'), 'daily_summaries', ['summary_date'], unique=False)
    op.create_index(op.f('ix_daily_summaries_user_id'), 'daily_summaries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_summaries_user_id'), table_name='daily_summaries')
    op.drop_index(op.f('ix_daily_summaries_summary_date'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    # ### end Alembic commands ###
