"""add role and ai_usage_count to users

Revision ID: c4e7e716240d
Revises: 3ecbe3e132a5
Create Date: 2026-07-28 15:25:00.713084

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c4e7e716240d'
down_revision: str | Sequence[str] | None = '3ecbe3e132a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    op.add_column('users', sa.Column('ai_usage_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_usage_count')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
